# Generated by Django 3.0.6 on 2020-05-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
