# Generated by Django 3.0.6 on 2020-06-01 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20200531_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
